services:
  3astronautasdb:
    image: mongo:5.0.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    container_name: 3astronautas-database
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
